# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: task-ls

  task-ls:
    desc: List available tasks
    cmds:
      - task --list

  docker-build:
    desc: Build the Docker image
    cmds:
      - set -a && source .docker/docker.env && docker-compose --project-directory . -f .docker/docker-compose.yaml build && set +a

  docker-run:
    desc: Run the Docker image
    cmds:
      - set -a && source .docker/docker.env && docker-compose --project-directory . -f .docker/docker-compose.yaml run app && set +a

  docker-up:
    desc: Start the Docker services
    cmds:
      - set -a && source .docker/docker.env && docker-compose --project-directory . -f .docker/docker-compose.yaml up && set +a

  docker-exec:
    desc: Run a command in the Docker container
    cmds:
      - set -a && source .docker/docker.env && docker-compose --project-directory . -f .docker/docker-compose.yaml exec app bash && set +a
