version: "3"

services:
  workspace:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        ARG_BUILD_FROM: $BUILD_FROM
        ARG_USERNAME: $USERNAME
        ARG_USER_UID: $USER_UID
        ARG_USER_GID: $USER_GID
        ARG_WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
        ARG_SDW_GITHUB_USERNAME: $SDW_GITHUB_USERNAME
        ARG_SDW_GITHUB_REPO: $SDW_GITHUB_REPO
        ARG_SDW_INSTALL_ROOT: $SDW_INSTALL_ROOT
        ARG_SDW_CLONE_DIR: $SDW_CLONE_DIR
        ARG_SDW_GITHUB_BRANCH: $SDW_GITHUB_BRANCH
        ARG_SDW_SERVER_NAME: $SDW_SERVER_NAME
    image: $IMAGE_NAME
    hostname: $CONTAINER_HOSTNAME
    command:
      - bash
      - $CONTAINER_WORKSPACE_ROOT/scripts/webui.sh
    ulimits:
      stack: 67108864
      memlock: -1
    ipc: host
    ports:
      - "$HOST_SSH_PORT:$SSH_PORT"
      - "$HOST_GRADIO_PORT:$GRADIO_PORT"
    volumes:
      - "$HOME/.cache/huggingface:/home/$USERNAME/.cache/huggingface"
      - "$HOME/.huggingface:/home/$USERNAME/.huggingface"
      - "$WORKSPACE_ROOT:$CONTAINER_WORKSPACE_ROOT"
      - "$PWD/.docker/scripts:$CONTAINER_WORKSPACE_ROOT/scripts"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${CUDA_DEVICE_ID}"]
              capabilities: [gpu]
networks:
  default:
    name: $DOCKER_NETWORK_NAME
    external: true
